apiVersion: batch/v1
kind: Job
metadata:
  name: guess-number-job
spec:
  ttlSecondsAfterFinished: 60
  template:
    spec:
      containers:
        - name: guess-number
          image: guess-number-console:v1
          command: ["java", "GuessNumberGameConsole"]
      restartPolicy: Never
